### ISSUE TITLE
Avoid installing usbser-based drivers on Windows 10?

### ISSUE THREAD

**Issue by dhalbert** [adafruit/Adafruit_Windows_Drivers#1]
As we know, Windows 10 now automatically installs USB devices that use usbser.sys. So several of the drivers in this package are not needed on Windows 10. Some of the "Learn" tutorials mention this, some don't.

There were several recent support issues around the UF2 bootloader that seemed related to the drivers being installed on Windows 10. Somewhat mysteriously (to me), uninstalling the drivers made the problem go away.

Examples: https://github.com/adafruit/circuitpython/issues/123 (EDIT: different problem)
https://forums.adafruit.com/viewtopic.php?f=60&t=116801

The PJRC CDC driver installer [notices](https://forums.adafruit.com/viewtopic.php?f=19&t=80341#p407086) if it is being run on Windows 10 and does not actually install anything.

So perhaps the installer should check the Windows version and remove or gray-out the checkboxes for the unneeded drivers? Some explanatory text could be added.

**Comment by ladyada** [comment]
huh, that first link makes it seem like its win7 not win10?

**Comment by ladyada** [comment]
(that said, im totally for making it not-install on win 10, just trying to nail down what it is :)

**Comment by dhalbert** [comment]
You're right, sorry, the first link must be something else.

**Comment by ladyada** [comment]
yah i really do think its a win 7 thing because it totally happened to me on one of my computers, during dev, and i did a full cleanup of all my drivers and it 'went away' - i wonder if we'll see only 'advanced' people with this bug because it requires a bit of a crusty win7 install

**Comment by dhalbert** [comment]
I saw (https://github.com/adafruit/circuitpython/issues/123#issuecomment-299081183) FEATHERBOOT be missing on a very vanilla Win7 system we have that had all the Adafruit drivers installed but nothing else (Arduino IDE was never installed; it's our DVR computer). I uninstalled the drivers one at a time and then put them back, and it was OK again. I made sure it was the same installer.

**Comment by robomike** [comment]
Hi all, 

I installed the AdaFruit drivers from 2007 when I wanted to compare Circuit Python to Arduino on the Metro Express board.  I'm on a Windows 10 machine (and so is my laptop).  I installed the new drivers on both machines and both machines had the same problem:  Arduino IDE didn't communicate with Metro Express on the laptop, but it did on the other machine.  Bossac didn't work on the machine or the laptop.  The vagrant VM didn't recognize the metro USB, I had to add it as "unknown".  Also, the UF2 drive was no longer visible in windows.   Today @dhalbert told me to uninstall the drivers.  This instantly fixed all issues.  I thank @dhalbert very much!

**Comment by dhalbert** [comment]
Saw another case of a user whose M0 Express was not seen properly on Windows 7 until the older usbser drivers were removed: https://forums.adafruit.com/viewtopic.php?f=60&t=118739. I spent a little time on the installer script to suppress usbser installation on Windows 10 and submitted a pull request.

**Comment by ladyada** [comment]
ok re-signed/generated the windriver - do you mind trying release 1.3 :)
