### ISSUE TITLE
[Bug] Device naming in Windows device manager

### ISSUE THREAD

**Issue by tryallthethings** [adafruit/Adafruit_Windows_Drivers#15]
Hello!

I just installed the latest available version of your USB drivers (2.3.3.0) on my Windows 8.1 machine with a Adafruit Hallowing connected. This is what the device manager is showing now:

![image](https://user-images.githubusercontent.com/11146296/49291524-eea1d100-f4aa-11e8-8f87-e2ea6020f312.png)

![image](https://user-images.githubusercontent.com/11146296/49291499-d5008980-f4aa-11e8-80df-d7c2a0b59208.png)

I suppose this isn't the expected device naming. Apart from the name the driver seems to work fine.

Regards,
Stefan

**Comment by ladyada** [comment]
i think its ok - probably a windows 8 thing cause the string is properly picked up when you use 7 or 10 - we did a little string macro thing :)

@roots, did it happen before or is this new?

**Comment by tryallthethings** [comment]
I installed the drivers today for the first time. But to double-check I tried 2.3.1.0 just now. Same issue here as well.

**Comment by dhalbert** [comment]
I have seen this naming issue in Windows 10 as well (when the driver was installed and it wasn't supposed to be), but not in Windows 7. I think it's some kind of string expansion bug that surface in Win8 and later, but it doesn't seem to affect the functioning of the driver. I tried a few fixes and ultimately didn't feel it was worth the time to try to fix.

**Comment by tryallthethings** [comment]
If it's too much effort to fix I would suggest adding a warning or information to the installation or download page so less tech-savvy users aren't confused by the naming.

**Comment by dhalbert** [comment]
Good idea, I'll put something on the appropriate Learn Guide page.

**Comment by dhalbert** [comment]
Closing this as cosmetic.
