### ISSUE TITLE
Itsy Bitsy M4 device not recognized in device manager (code 28)

### ISSUE THREAD

**Issue by MikeTheFox** [adafruit/Adafruit_Windows_Drivers#17]
I can't seem to get the drivers for the ItsyBitsy M4 express installed on windows 7. Works fine on windows 10. Installed the driver package but i get `The drivers for this device are not installed. (Code 28)` as error message in device manager. Because the AdaFruit driver package contains many drivers i don't know what to select when trying to install these drivers manually... (Updated the firmware on the ItsyBitsy using  that windows 10 machine but no difference.)

**Comment by dhalbert** [comment]
You don't need to install drivers on Windows 10.

Try uninstalling and reinstalling the drivers as described here: https://learn.adafruit.com/welcome-to-circuitpython/troubleshooting#cplayboot-trinketboot-featherboot-or-gemmaboot-drive-not-present-20-4

For WIndows 7, you need to check only the first box in the Installation Options dialog box:
![image](https://user-images.githubusercontent.com/2847802/60281125-5352cc00-98d2-11e9-9582-dc8ac91be227.png)

**Comment by MikeTheFox** [comment]
Yes, the device works fine on Windows 10 without installing the drivers. But when i install them on Windows 7 device manager shows that the device was not installed correctly. See images.

![image](https://user-images.githubusercontent.com/17983485/60368543-6b6d3d00-99f1-11e9-975b-457e6c056d1e.png)

(Andere apparaten = Other Devices. Note: the name changed to Itsy BItsy after installing the driver.)

![image](https://user-images.githubusercontent.com/17983485/60368680-c56e0280-99f1-11e9-9047-f50ceee8a810.png)

![image](https://user-images.githubusercontent.com/17983485/60368718-e5052b00-99f1-11e9-9ffd-4057dd50cd46.png)

It is not that i did not know what to select in the installer. But under device manager it is possible to manually select the driver, but then you need to know which one...

![image](https://user-images.githubusercontent.com/17983485/60368819-2ac1f380-99f2-11e9-934c-e24e73a8bcd7.png)
