### ISSUE TITLE
Adafruit_usbser.inf, PID mismatch for new boards

### ISSUE THREAD

**Issue by hiduino** [adafruit/Adafruit_Windows_Drivers#19]
It appears the recent changes to Drivers/Adafruit_usbser/Adafruit_usbser.inf to add the new boards have the wrong PID for the UF2 WebUSB dummy drivers.

For example the Hallowing M4 shows:
"%ADAFRUIT_BOARD_804A% UF2 Bootloader (0049:00)"=DriverInstall, USB\VID_239A&PID_0049&MI_00
"%ADAFRUIT_BOARD_804A% UF2 WebUSB dummy (**004A**:04)"=NullInstall, USB\VID_239A&**PID_004A**&MI_04

Should be (as shows up in the Device Manager):
"%ADAFRUIT_BOARD_804A% UF2 WebUSB dummy (**0049**:04)"=NullInstall, USB\VID_239A&**PID_0049**&MI_04

**Comment by ladyada** [comment]
woops, can you submit a PR :) otherwise we'll get to it when @dhalbert is back
