### ISSUE TITLE
USB device not recognized, ItsyBitsy M0 Express, Windows 10

### ISSUE THREAD

**Issue by OutstandingBillNeal** [adafruit/Adafruit_Windows_Drivers#21]
Hi,

I have two ItsyBitsy M0 Express boards.  One seems to be broken, and the other works fine.  The apparently-broken one isn't recognised by Windows 10 when connected via USB.  I've tried connecting it to two different Windows 10 computers, both behave the same.  Using the same USB cable, Windows recognises the other Itsy, and used to recognise the apparently-broken one.

I might have done something bad while developing on the broken one.  I was getting it to print debugging messages in an unrestrained loop (with no "wait" command).  At some stage I saw a "safe mode" message, but being really deep in the problem I was debugging, I didn't want to change focus, so pay much attention.  I hit the reset button, it came back up, then died again shortly after, never to return.

When I connect the broken one to my PC, a message pops up saying "USB device not recognized - The last USB device you connected to this computer malfunctioned, and Windows does not recognize it."

![image](https://user-images.githubusercontent.com/58252931/73168037-eb14e300-415d-11ea-8192-3038c218573c.png)

And in Device Manager, it says "Unknown USB Device (Device Descriptor Request Failed)"

![image](https://user-images.githubusercontent.com/58252931/73168156-231c2600-415e-11ea-8bb4-588b2d688c03.png)

Is there anything I can do?

**Comment by dhalbert** [comment]
If you double-click the reset button, you should see the LED next to the button pulsing slowly, and ITSYBOOT should so show up. Are you seeing that?

If you can get that to show up, do the same for the other Itsy, and copy CURRENT.UF2 from the good one onto the computer, and then copy it to ITSYBOOT on the "bad" board. That will clone the good one onto the problematic one.

**Comment by OutstandingBillNeal** [comment]
When I double-click the reset button, yes, I do see the red LED pulse slowly, and the ITSYBOOT drive shows up in Windows Explorer.  

When I copy CURRENT.UF2 from the working board, I first see the "replace file in the destination?" dialog, then the file copy progress showing 0%, 43%, then disappearing.  

But alas, then the same thing happens as before - the notification pops up saying the device isn't recognised.

**Comment by OutstandingBillNeal** [comment]
@dhalbert , does that mean it's broken beyond repair?

**Comment by OutstandingBillNeal** [comment]
@dhalbert sorry to keep bugging you - is there any further advice you can offer on this issue? (And by the way, thanks for supporting the community :)

**Comment by dhalbert** [comment]
Sorry for not replying earlier! Have you tried this on another computer? If it still doesn't work, maybe there is something wrong with the "bad" board. Could you post in the forums about this? We can see about getting you a replacement there. Post a link to the forum thread here.

**Comment by OutstandingBillNeal** [comment]
Thanks Dan, I've tried the boot copy procedure on a couple of Windows 10 machines now, with the same results. Thank you for your help with this.

**Comment by OutstandingBillNeal** [comment]
Adafruit support conversation: https://forums.adafruit.com/viewtopic.php?f=62&t=162018

**Comment by dhalbert** [comment]
We'll work with you on a replacement. Continuing the conversation in that thread.
