### ISSUE TITLE
Feather Bluefruit Sense missing from this driver

### ISSUE THREAD

**Issue by FoamyGuy** [adafruit/Adafruit_Windows_Drivers#27]
I think this is missing the Feather Bluefruit Sense device. Windows 7 will not recognize a Sense device and assign it a COM port when using the standard Circuit Python image. 

If you use the Feather nrf52840 Express Circuit Python image on the Sense device then the device does get recognized and COM port assigned.

**Comment by KingJimmy27** [comment]
Device manager says the driver is from Microsoft usbser.sys.
Is this correct because I am having trouble with Serial Monitor in VisualMicro and wish to eliminate the driver as being at fault.
Posts: 14
Joined: Thu Nov 21, 2013 11:36 am
Location: England

**Comment by dhalbert** [comment]
@KingJimmy27 On what version of Windows did you install the driver package? On Windows 10, you do not need to install the driver package: Windows already includes a correct generic driver. The driver package notices it is on Windows 10 and doesn't install anything to replace that driver.

**Comment by KingJimmy27** [comment]
I am on Win 10 but have trouble with Visual Micro so wanted to confirm that I was using the correct drivers.
Initially I connect to COM3. 
From Visual Studio running Visual Micro I get:
Uploading 'SensorExampleFromWeb' to 'Adafruit Feather Bluefruit Sense' using 'COM3'
Unable to 'touch' hardware serial port: COM3. Now assuming selected port is bootloader port. This might still fail, have you got the correct board selected?
Upgrading target on COM4 with DFU package C:\Users\james\AppData\Local\Temp\VMBuilds\SensorExampleFromWeb\adafruit_feather52840sense\Release\SensorExampleFromWeb.ino.zip. Flow control is disabled, Single bank, Touch disabled

From Arduino 1.8.13 I get:
Upgrading target on COM4 with DFU package C:\Users\james\AppData\Local\Temp\arduino_build_378866\sketch_aug18a.ino.zip. Flow control is disabled, Single bank, Touch disabled.

Any advice?

**Comment by dhalbert** [comment]
I'll repeat you do not need to install any drivers on Windows 10.

Regular Arduino requires that you install the Adafruit nRF board support package. I have no idea if you can install the same package with Visual Micro. Have you installed the board support package on Arduino, and have you set the board type to be the Feather Sense board?

This kind of support is better done in our forums: https://forums.adafruit.com, as the issue here is not a bug in the drivers.

**Comment by dhalbert** [comment]
superceded by #28

**Comment by ladyada** [comment]
please check the latest release :)

**Comment by FoamyGuy** [comment]
It's working well now, Feather Sense is recognized by windows after installing the new release driver.
