### ISSUE TITLE
Windows on ARM support?

### ISSUE THREAD

**Issue by sidd-kishan** [adafruit/Adafruit_Windows_Drivers#32]
Please let us know when can we have windows on ARM support with ARM64 drivers.

**Comment by ladyada** [comment]
which exact board/driver?

**Comment by sidd-kishan** [comment]
It would be great to have an ARM64 windows driver for Bluetooth/Wifi combination (https://www.adafruit.com/product/2649) for networking and wifi.

**Comment by ladyada** [comment]
ok that isn't a driver included in this repo anyways, its
Ralink RT5370L WiFi adapter + BCM2046B1 Bluetooth 3.0 adapter
so you would have to ask Ralink and Broadcom to add driver support (we cannot write the driver for a chip we dont make)
